name: Windows

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
      
jobs:
  test-on-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    name: Test BusyLight for Humans ${{ matrix.python-version }} on Windows
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry/pytest
        run: |
          python -m pip install -U poetry pytest
      - name: Install BusyLight-For-Humans with WebAPI
        run: |
          poetry install -E webapi
      - name: Test with pytest
        run: |
          poetry run pytest
  deploy:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: python -m build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.exe"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create new patch release
        run: .github/scripts/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
          
            
